version: "3"

tasks:
  test:
    cmds:
      - go test ./...

  lint:
    cmds:
      - go vet ./...

  run:
    cmds:
      - go run .

  build:
    cmds:
      - go build -o bin/eudi-conformance-evidence .

  fmt:
    cmds:
      - go fmt ./...
      - go vet ./...
